CVODE Trajectory Generator: SingleBody::SingleBody
denseJac
getOptionString
getVectorSize
handleOption
recordData
rhsFunc
setCaptureRadius
setLaunchRadius
setLaunchSpeed
SingleBody
updateInitialVector
SingleBody::SingleBody () inline
Default constructor that picks some reasonable values for the constants.
Definition at line 115 of file SingleBody.h.
References AbstractProblem::setFinalTime(), AbstractProblem::setInitialTime(), setLaunchSpeed(), AbstractProblem::setTimestep(), and AbstractProblem::setTolerance().
                :
        AbstractProblem(),
        _launch_radius(0.1),
        _capture_radius(0.005)
    {
        setLaunchSpeed(1.0);
        setTolerance(RCONST(1e-12), RCONST(1e-14));
        setInitialTime(0.0);
        setFinalTime(32.0);
        setTimestep(0.0001);
}