CVODE Trajectory Generator: CurvedTwoBody::CurvedTwoBody
CurvedTwoBody
denseJac
getOptionString
getVectorSize
handleOption
recordData
recordDataInit
rhsFunc
setCaptureRadius
setDeltaV
setInitialSeparation
setMassFraction
setSphereRadius
updateInitialVector
CurvedTwoBody::CurvedTwoBody () inline
Default constructor that picks some reasonable values for the constants.
Definition at line 124 of file CurvedTwoBody.h.
References AbstractProblem::setFinalTime(), AbstractProblem::setInitialTime(), AbstractProblem::setTimestep(), AbstractProblem::setTolerance(), and updateInitialVector().
                   :
        AbstractProblem(),
        _capture_radius(0.005),
        _mass_1(0.3),
        _mass_2(0.7),
        _initial_separation(1.0),
        _delta_v(1.0),
        _sphere_radius(1.0)
    {
        updateInitialVector();
        setTolerance(RCONST(1e-12), RCONST(1e-14));
        setInitialTime(0.0);
        setFinalTime(32.0);
        setTimestep(0.01);
}