CVODE Trajectory Generator: main
main
PROBLEM_TYPE
split_realtype
int main (int argc, char ** argv)
Parse command-line options, initialize problem and integrator, and finally run the integration.
Definition at line 207 of file main.cpp.
References Integrator< P >::cleanup(), Integrator< P >::done(), Integrator< P >::enableLogTime(), Integrator< P >::initIntegration(), PROBLEM_TYPE, Integrator< P >::runStep(), Integrator< P >::setCvodeMaxInternalSteps(), LogTime::setFactorByN(), LogTime::setFirstTime(), Integrator< P >::setIntegrationMethod(), Integrator< P >::setIterator(), Integrator< P >::setPointCount(), and split_realtype().
{
    PROBLEM_TYPE p;
    try {
        Integrator<PROBLEM_TYPE>* integrator;
        integrator = new Integrator<PROBLEM_TYPE>(p);
        // Let's do some option parsing!
        int arg, opt_index;
        string optstring = "p:I:i:v:r:T:t:b:e:s:N:m:L:n:";
        optstring += p.getOptionString();
        while (1)
        {
            static struct option long_options[] = {
                {"integration-method", 1, 0, 'I'},
                {"iterator",           1, 0, 'i'},
                {"initial-vector",     1, 0, 'v'},
                {"relative-tolerance", 1, 0, 'r'},
                {"absolute-tolerance", 1, 0, 't'},
                {"begin",              1, 0, 'b'},
                {"end",                1, 0, 'e'},
                {"timestep",           1, 0, 's'},
                {"number-points",      1, 0, 'N'},
                {"data-length",        1, 0, 'N'},
                {"max-internal-steps", 1, 0, 'm'},
                {"logtime-start",      1, 0, 'L'},
                {"logtime-n",          1, 0, 'n'}
            };
            arg = getopt_long(argc, argv, optstring.c_str(), long_options, &opt_index);
            if (arg == -1)
                break;
            switch (arg) {
                case 'p': // problem
                    cout << "-p: Sorry, choosing problem at runtime isn't supported. (yet)" << endl;
                    break;
                case 'I': // Integrator
                    if (string(optarg) == string("bdf"))
                        integrator->setIntegrationMethod(CV_BDF);
                    else if (string(optarg) == string("adams"))
                        integrator->setIntegrationMethod(CV_ADAMS);
                    else
                        cerr << "-I: Valid integration methods are \"bdf\" and \"adams\"" << endl;
                    break;
                case 'i': // iterator
                    if (string(optarg) == string("newton"))
                        integrator->setIterator(CV_NEWTON);
                    else if (string(optarg) == string("functional"))
                        integrator->setIterator(CV_FUNCTIONAL);
                    else
                        cerr << "-i: Valid iterators are \"newton\" and \"functional\"" << endl;
                    break;
                case 'v': // initial conditions vector
                    p.setInitialVector(split_realtype(",", optarg));
                    break;
                case 'r': // relative tolerance (float scalar)
                    p.setRelativeTolerance(atof(optarg));
                    break;
                case 'T': // absolute tolerance (comma-separated vector)
                    p.setAbsoluteTolerance(split_realtype(",", optarg));
                    break;
                case 't': // absolute tolerance (float scalar)
                    p.setAbsoluteTolerance(atof(optarg));
                    break;
                case 'b': // beginning time
                    p.setInitialTime(atof(optarg));
                    break;
                case 'e': // ending time
                    p.setFinalTime(atof(optarg));
                    break;
                case 's': // timestep
                    p.setTimestep(atof(optarg));
                    break;
                case 'N':
                    integrator->setPointCount(atoll(optarg));
                    break;
                case 'm':
                    integrator->setCvodeMaxInternalSteps(atoll(optarg));
                    break;
                case 'L':
                    integrator->enableLogTime();
                    integrator->logtime.setFirstTime(atof(optarg));
                    break;
                case 'n':
                    integrator->enableLogTime();
                    integrator->logtime.setFactorByN(atof(optarg));
                    break;
                case ':':
                case '?':
                    cerr << "Error: Something messed up in the options." << endl;
                    return 1;
                default:
                    if (!p.handleOption(arg))
                    {
                        cerr << "Error: Don't know what to do with option: -"
                             << arg << endl;
                    }
            }
        }
        // End option parsing.
#ifdef DEBUG
        cerr << "Address of initial vector: " << p.getInitialVector() << endl;
#endif
        integrator->initIntegration();
        while (!integrator->done())
        {
            integrator->runStep();
        }
        integrator->cleanup();
    }
    catch (exception &e) {
        // Only complain if the problem isn't aware of it.
        if (p.getErrorCode() == 0)
        {
            cerr << "Caught exception!" << endl;
            cerr << e.what() << endl;
        }
    }
    // The problem's error code is 0 if nothing bad happened, and nonzero
    // if something did go awry. So let's use it as the program's return
    // value!
    return p.getErrorCode();
}